apiVersion: batch/v1
kind: Job
metadata:
  generateName: testing-on-post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: trigger-tests
        image: curlimages/curl
        command:
          - "curl"
          - "-d"
          - "{"message":"this is my first webhook"}"
          - "-H"
          - "Content-Type: application/json"
          - "-X"
          - "POST"
          - "http://10.244.0.56:12000/example"
      restartPolicy: Never
  backoffLimit: 2
